workflows:
  android-debug:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Set permissions
        script: |
          chmod +x gradlew
      - name: Build Android Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
